// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS6YbY6hcP3BEyj4dCryHWdvprjNIvFr0',
    appId: '1:475511500132:web:8e202637ac1ce60becde71',
    messagingSenderId: '475511500132',
    projectId: 'world-pff',
    authDomain: 'world-pff.firebaseapp.com',
    storageBucket: 'world-pff.appspot.com',
    measurementId: 'G-ZFWRZSFPES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKqYov48nq4JL9rAFhHPDM20KzmIDt8dI',
    appId: '1:475511500132:android:f0c597715fd0750decde71',
    messagingSenderId: '475511500132',
    projectId: 'world-pff',
    storageBucket: 'world-pff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU9eiCdYAoqv4B_mXgQAQGRhWLvdPTGuw',
    appId: '1:475511500132:ios:cede2eec80573c55ecde71',
    messagingSenderId: '475511500132',
    projectId: 'world-pff',
    storageBucket: 'world-pff.appspot.com',
    iosBundleId: 'com.example.webrtcMessagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU9eiCdYAoqv4B_mXgQAQGRhWLvdPTGuw',
    appId: '1:475511500132:ios:cede2eec80573c55ecde71',
    messagingSenderId: '475511500132',
    projectId: 'world-pff',
    storageBucket: 'world-pff.appspot.com',
    iosBundleId: 'com.example.webrtcMessagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS6YbY6hcP3BEyj4dCryHWdvprjNIvFr0',
    appId: '1:475511500132:web:d9c7789a07fa05c1ecde71',
    messagingSenderId: '475511500132',
    projectId: 'world-pff',
    authDomain: 'world-pff.firebaseapp.com',
    storageBucket: 'world-pff.appspot.com',
    measurementId: 'G-TJLNJ6M32L',
  );
}
